version: 2.1
jobs:
    run tests:
    docker:
        - image: circleci/node:18
    steps:
        - checkout
        - run:
            name: Install npm dependencies
            command: | 
                npm install
        - run:
            name: Run Unit Tests
            command: |
                npm run wdio
workflows:
    build_test: 
        jobs:
            - run_tests